#!/usr/bin/env python3
"""Cross-references requirements.csv against one or more trace JSON files
and generates docs/traceability_matrix.md.

Each trace JSON is a list of {"test": str, "passed": bool,
"requirements": [str, ...]} records. Two kinds of trace files feed this in
practice: the GoogleTest requirement-trace listener (include/req_trace.hpp,
tests/test_main.cpp, written by default to build/test_trace.json) for
requirements that are unit-testable in isolation, and the Python end-to-end
drivers (driver/run_boundary_violations.py, driver/run_fault_injection.py),
for requirements that are only meaningfully checkable against the live,
two-process system. Passing --trace more than once merges all of them,
which is the normal way this is invoked (see README "Building and
running").

Usage:
    python3 tools/gen_traceability.py \
        --trace build/test_trace.json \
        --trace build/e2e_boundary/e2e_boundary_trace.json \
        --trace build/e2e_fault/e2e_fault_trace.json \
        --requirements requirements.csv --out docs/traceability_matrix.md

Exit code is non-zero if any requirement has zero passing covering tests --
wired as a real gate (REQ-021), not a report generator only.
"""
import argparse
import csv
import json
import sys
from pathlib import Path


def load_requirements(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def load_trace(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def build_matrix(requirements, trace_records):
    coverage = {r["id"]: [] for r in requirements}
    untraced_tests = []

    for rec in trace_records:
        reqs = rec.get("requirements", [])
        if not reqs:
            untraced_tests.append(rec["test"])
            continue
        for req_id in reqs:
            coverage.setdefault(req_id, []).append((rec["test"], rec["passed"]))

    return coverage, untraced_tests


def status_for(covering_tests):
    if not covering_tests:
        return "UNTESTED"
    if all(passed for _, passed in covering_tests):
        return "PASS"
    return "FAIL"


def render_markdown(requirements, coverage, untraced_tests, sources):
    lines = []
    lines.append("# Requirements Traceability Matrix")
    lines.append("")
    lines.append(
        "Auto-generated by `tools/gen_traceability.py` from `requirements.csv` "
        "and " + ", ".join(f"`{s}`" for s in sources) + ". Do not hand-edit, "
        "regenerate instead."
    )
    lines.append("")
    lines.append("| Requirement | Description | Component | Covering Tests | Status |")
    lines.append("|---|---|---|---|---|")

    untested = []
    for r in requirements:
        req_id = r["id"]
        covering_tests = coverage.get(req_id, [])
        status = status_for(covering_tests)
        if status == "UNTESTED":
            untested.append(req_id)
        test_list = "<br>".join(
            f"{name} {'PASS' if passed else 'FAIL'}" for name, passed in covering_tests
        ) or "*(none)*"
        lines.append(f"| {req_id} | {r['description']} | {r['component']} | {test_list} | {status} |")

    lines.append("")
    lines.append("## Coverage gaps")
    lines.append("")
    if untested:
        lines.append("Requirements with **zero** passing covering tests:")
        lines.append("")
        for req_id in untested:
            lines.append(f"- {req_id}")
    else:
        lines.append("None, every requirement has at least one passing covering test.")

    lines.append("")
    lines.append("## Untraced tests")
    lines.append("")
    lines.append(
        "Tests that ran but did not tag any requirement (not necessarily a "
        "problem, e.g. basic sanity checks, but worth a look):"
    )
    lines.append("")
    if untraced_tests:
        for name in untraced_tests:
            lines.append(f"- {name}")
    else:
        lines.append("None.")

    lines.append("")
    return "\n".join(lines), untested


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--trace", action="append", required=True, help="may be passed more than once")
    parser.add_argument("--requirements", default="requirements.csv")
    parser.add_argument("--out", default="docs/traceability_matrix.md")
    args = parser.parse_args()

    requirements = load_requirements(args.requirements)
    all_records = []
    for trace_path in args.trace:
        all_records.extend(load_trace(trace_path))

    coverage, untraced_tests = build_matrix(requirements, all_records)
    markdown, untested = render_markdown(requirements, coverage, untraced_tests, args.trace)

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(markdown, encoding="utf-8")

    any_failed = any(status_for(coverage.get(r["id"], [])) == "FAIL" for r in requirements)
    print(
        f"wrote {out_path} -- {len(requirements)} requirements, {len(untested)} untested, "
        f"{len(untraced_tests)} untraced tests, from {len(args.trace)} trace file(s)"
    )
    if untested:
        print(f"untested: {untested}")

    if untested or any_failed:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
